name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        xcodebuild -version
        xcode-select -print-path
        xcodebuild test -scheme FluxorSampleToDo -destination "platform=iOS Simulator,name=iPhone 11 Pro,OS=13.1"
        
